plugins {
id 'com.android.application'
}

android {
namespace "none.tube"
compileSdk 35

lint {
   checkReleaseBuilds false
}

defaultConfig {  
    applicationId "none.tube"  
    minSdk 29
    targetSdk 37
    versionCode 1
    versionName "1.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
   }  
} }


dependencies {
}
